---

- name: Start nginx
  systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Start Buildbot
  systemd:
    name: buildbot
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes

- name: Start Autossh
  systemd:
    name: autossh
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  when: "'master' not in group_names"
