---

- name: Start Buildbot
  docker_compose:
    project_src: "{{ buildbot_home }}"
    pull: yes
    state: present
    restarted: yes
  become: yes

- name: Start Databases
  docker_compose:
    project_src: "{{ buildbot_home }}"
    pull: yes
    state: present
    restarted: yes
  become: yes

- name: Start Autossh
  systemd:
    name: autossh
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
  when: "'master' not in group_names"

- name: Restart Docker
  systemd:
    name: docker
    state: restarted
    enabled: yes
    daemon_reload: yes
  become: yes
