---

- name: Pruning Docker containers and images
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
  become: yes

- name: Removing local builds of Docker images
  docker_image:
    name: "ocqa-{{ item }}-worker"
    tag: "{{ docker_worker_image_tag }}"
    source: local
    state: absent
    force_absent: yes
  with_items:
    - "{{ docker_worker_images }}"
  become: yes

- name: Updating Docker images
  docker_image:
    name: "{{ docker_image_user }}/ocqa-{{ item }}-worker-base"
    tag: "{{ docker_worker_image_tag }}"
    source: pull
    state: present
    force_source: yes
  when: "'workers' in group_names"
  with_items:
    - "{{ docker_worker_images }}"
  become: yes

- name: Updating Docker master image
  docker_image:
    name: "{{ docker_image_user }}/ocqa-buildbot-master"
    tag: "{{ docker_image_tag }}"
    source: pull
    state: present
    force_source: yes
  when: "'master' in group_names"
  become: yes
