---

- include_tasks: update.yml
  loop: "{{ docker_worker_images }}"

- name: Updating Docker master image
  docker_image:
    name: "{{ docker_image_user }}/ocqa-buildbot-master"
    tag: "{{ docker_image_tag }}"
    source: pull
    state: present
    force_source: yes
  when: "'master' in group_names"
  become: yes

- name: Pruning Docker containers and images
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
  become: yes
