---

- name: Pruning Docker containers and images
  docker_prune:
    containers: yes
    images: yes
    networks: yes
    volumes: yes
  become: yes

- name: Updating Docker images
  docker_image:
    name: "ocqa-{{ item }}-worker:{{ docker_worker_image_tag }}"
    source: pull
    state: absent
  with_items:
    - "{{ docker_worker_images }}"
  become: yes

- name: Updating Docker images
  docker_image:
    name: "{{ docker_image_user }}/ocqa-{{ item }}-worker-base:{{ docker_worker_image_tag }}"
    source: pull
    state: present
  when: "'workers' in group_names"
  with_items:
    - "{{ docker_worker_images }}"
  become: yes

- name: Updating Docker master image
  docker_image:
    name: "{{ docker_image_user }}/ocqa-buildbot-master:{{ docker_image_tag }}"
    source: pull
    state: present
  when: "'master' in group_names"
  become: yes
