---

- name: Building {{ item }} worker image
  docker_image:
    build:
      path: "{{ buildbot_config_worker }}/workers/{{ item }}"
      pull: yes
      rm: yes
    name: "ocqa-{{ item }}-worker"
    tag: "{{ docker_worker_image_tag }}"
    source: build
    state: present
    force_source: yes
  when: "'workers' in group_names"
  become: yes

- name: Pruning Docker containers and images
  docker_prune:
    containers: yes
    images: yes
  become: yes
