---


- name: Pulling {{ distro }} worker base image
  shell: docker pull {{ docker_image_user }}/ocqa-{{ distro }}-worker-base:{{ docker_worker_image_tag }}
  become: yes

- name: Finding all built {{ distro }} worker images
  shell: docker images -q {{ hostvars[inventory_hostname]['name'] }}_*
  become: yes
  register: worker_images

- name: Removing all built {{ distro }} worker image to force rebuild
  shell: docker rmi -f {{ item }}
  become: yes
  with_items:
    - "{{ worker_images.stdout_lines }}"
  when: worker_images.stdout_lines | length > 0

- name: Finding other {{ distro }} worker base images
  shell: docker images -q --filter "before={{ docker_image_user }}/ocqa-{{ distro }}-worker-base:{{ docker_worker_image_tag }}" {{ docker_image_user }}/ocqa-{{ distro }}-worker-base
  become: yes
  register: worker_base_images

- name: Removing other {{ distro }} worker base images
  shell: docker rmi -f {{ item }}
  become: yes
  with_items:
    - "{{ worker_base_images.stdout_lines }}"
  when: worker_base_images.stdout_lines | length > 0

