---


- name: Building {{ distro }} worker image
  shell: docker build --pull {{ distro }} -t ocqa-{{ distro }}-worker:{{ docker_worker_image_tag }}
  args:
    chdir: "{{ buildbot_config_worker }}/workers"
  when: "'workers' in group_names"
  become: yes

- include_tasks: remove.yml
  loop:
    - "ocqa-{{ distro }}-worker"
    - "{{ docker_image_user }}/ocqa-{{ distro }}-worker-base"
  loop_control:
    loop_var: image

- name: Pruning Docker containers
  shell: docker container prune -f
  when: "'workers' in group_names"
  become: yes

- name: Pruning Docker images
  shell: docker image prune -f
  when: "'workers' in group_names"
  become: yes
