---

- name: Loading platform variables
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}-{{ansible_distribution_release}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}.yml"

- name: Install EPEL release
  yum:
    name: epel-release
    state: latest
    update_cache: yes
  become: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install Buildbot system level dependencies
  package:
    name: "{{ lookup('vars', ansible_distribution_major_version) }}"
    state: latest
  become: yes
