version: '2'
services:
  buildbot:
    user: "{{ hostvars[inventory_hostname]['uid'] }}:{{ hostvars[inventory_hostname]['gid'] }}"
    image: "{{ docker_image_user }}/ocqa-buildbot-master:{{ docker_image_tag }}"
    restart: always
    env_file:
      - db.env
    environment:
      - BUILDBOT_WORKER_PORT=9989
    depends_on:
      - db
    #Note: This needs to be host because the SSH tunnels are coming to the docker *host* rather than the container
    network_mode: host
    volumes:
      - "{{ disk_base }}:{{ disk_base }}"
      - "{{ buildbot_home }}/buildbot-config:/buildbot"
  proxy:
    image: "nginx:stable"
    restart: always
    #This doesn't *need* to be host, but it's easier
    network_mode: host
    volumes:
      - "{{ buildbot_home }}/nginx-config/buildbot.conf:/etc/nginx/conf.d/buildbot.conf"
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "{{ buildbot_home }}/nginx-config/dhparam.pem:/etc/nginx/ssl/dhparam.pem"
      - "{{ disk_base }}:{{ disk_base }}"
      - "{{ buildbot_home }}/keys:{{ buildbot_home }}/keys"
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "{{ buildbot_home }}/postgres-data:/var/lib/postgresql/data"
