version: '2'
services:
  buildbot:
    user: "{{ hostvars[inventory_hostname]['uid'] }}:{{ hostvars[inventory_hostname]['gid'] }}"
    image: "{{ docker_image_user }}/ocqa-buildbot-master:{{ docker_image_tag }}"
    restart: always
    env_file:
      - db.env
    environment:
      - BUILDBOT_CONFIG_DIR=config
      - BUILDBOT_WORKER_PORT=9989
    depends_on:
      - db
    ports:
      - "{{ buildbot_port }}:{{ buildbot_port }}"
      #Note: We're only exposing the worker port to localhost on the master node since comms are done via SSH tunnel
      - "127.0.0.1:9989:9989"
{% if debug_enabled %}
      - "127.0.0.1:1234:1234"
{% endif %}
    network_mode: "host"
    volumes:
      - "{{ disk_base }}:{{ disk_base }}"
      - "{{ buildbot_home }}/buildbot-config:/var/lib/buildbot"
  proxy:
    image: "nginx:stable"
    restart: always
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - "{{ buildbot_home }}/nginx-config:/etc/nginx/conf.d"
      - "{{ disk_base }}:{{ disk_base }}"
  db:
    env_file:
      - db.env
    image: "postgres:9.4"
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - "{{ buildbot_home }}/postgres-data:/var/lib/postgresql/data"

{% if inventory_hostname in groups['workers'] %}
  maria:
    image: mariadb:10
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=1

  mysql56:
    image: mysql:5.6
    restart: always
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=1

  mysql57:
    image: mysql:5.7
    restart: always
    ports:
      - "127.0.0.1:3309:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=1
{% endif %}
