---

- name: Determine Buildbot UID
  getent:
    database: 'passwd'
    key: '{{ buildbot_user }}'
    split: ':'
  register: 'uid'

- name: Determine Buildbot GID
  getent:
    database: 'group'
    key: '{{ buildbot_user }}'
    split: ':'
  register: 'gid'

- name: Determine Docker GID
  getent:
    database: 'group'
    key: 'docker'
    split: ':'
  register: 'docker'

- name: Storing data
  set_fact:
    uid: "{{ uid['ansible_facts']['getent_passwd'][buildbot_user][1] }}"
    gid: "{{ gid['ansible_facts']['getent_group'][buildbot_user][1] }}"
    docker_gid: "{{ docker['ansible_facts']['getent_group']['docker'][1] }}"
