---
- name: Adding Docker repository to yum config
  yum_repository:
    name: docker-ce-stable
    file: "/etc/yum.repos.d/docker-ce.repo"
    description: "Docker CE Stable"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/stable"
    gpgkey: "https://download.docker.com/linux/centos/gpg"
    gpgcheck: yes
    enabled: yes
    state: present
  become: yes

- name: Installing Docker
  yum:
    name: [docker-ce, gcc]
    state: latest
  become: yes
