---

- name: Deploy Opencast test server
  hosts: all
  become: true
  roles:
    - role: nginx
    - role: elan.opencast_firewalld
      when: ansible_os_family == 'RedHat'
    - role: opencast
    - role: lkiesow.dnf_autoupdate
      when: ansible_os_family == 'RedHat'
