---

- hosts: all
  become: true
  roles:
    - nginx
    - opencast

#- hosts: all
#  become: true
#  roles:
#    - lkiesow.dnf_autoupdate
#  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'
