all:
  hosts:
    develop.opencast.org:
      opencast_version_major: 10
      version: 11-SNAPSHOT
    #stable.opencast.org:
    #  version: 9-SNAPSHOT
    #legacy.opencast.org:
    #  version: 8-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
