all:
  hosts:
    develop.opencast.org:
      # for repository:
      opencast_version_major: 13
      # for tarball:
      version: 14-SNAPSHOT
    stable.opencast.org:
      opencast_version_major: 13
      version: 13-SNAPSHOT
    legacy.opencast.org:
      opencast_version_major: 12
      version: 12-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
