all:
  hosts:
    develop.opencast.org:
      # for repository:
      opencast_version_major: 18
      # for tarball:
      version: 18-SNAPSHOT
    stable.opencast.org:
      opencast_version_major: 17
      version: 17-SNAPSHOT
    legacy.opencast.org:
      opencast_version_major: 16
      version: 16-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
