all:
  hosts:
    develop.opencast.org:
      # for repository:
      opencast_version_major: 12
      # for tarball:
      version: 13-SNAPSHOT
    #stable.opencast.org:
    #  version: 12-SNAPSHOT
    #legacy.opencast.org:
    #  version: 11-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
