all:
  hosts:
    develop.opencast.org:
      # for repository:
      opencast_version_major: 11
      # for tarball:
      version: 13-SNAPSHOT
    #stable.opencast.org:
    #  version: 9-SNAPSHOT
    #legacy.opencast.org:
    #  version: 8-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
