all:
  hosts:
    develop.opencast.org:
      # for repository:
      opencast_version_major: 17
      # for tarball:
      version: 17-SNAPSHOT
    stable.opencast.org:
      opencast_version_major: 16
      version: 16-SNAPSHOT
    legacy.opencast.org:
      opencast_version_major: 15
      version: 15-SNAPSHOT
  vars:
    opencast_repository_enabled_release: true
    opencast_repository_enabled_testing: true
