---
# vim: et:ts=2:sw=2:sts=2
# This playbook updates the buildbot worker images


- hosts: all
  user: "{{ login_user }}"
  roles:
    - { role: buildbot-new-images }
  handlers:
    - import_tasks: handlers/handlers.yml

