version: '2'
services:
  s3:
    image: "minio/minio"
    restart: always
    ports:
      - "9000:9000"
      - "43995:43995"
    volumes:
      - "{{ s3_home }}/minio:/data"
    environment:
      - MINIO_ROOT_USER={{ public_s3_access_key }}
      - MINIO_ROOT_PASSWORD={{ public_s3_secret_key }}
    command: server /data --console-address ":43995"
