---

- hosts: all
  become: true
  roles:
    - adopter-reg-server
    - nginxinc.nginx
    - nginxinc.nginx_config
  vars:
    - reg_server_user: "opencast"
    - reg_server_pass: "{{ lookup('passwordstore', 'register.opencast.org/opencast') }}"
    - reg_server_salt: "{{ lookup('passwordstore', 'register.opencast.org/salt') }}"
    - nginx_manage_repo: false
    - nginx_install_from: os_repository
    - nginx_setup_license: false
    - nginx_selinux: true
    - nginx_config_http_template_enable: true
    - nginx_config_http_template:
      - deployment_location: /etc/nginx/conf.d/oc-reg-server.conf
        config:
          servers:
            - core:
                listen:
                  - address: 0.0.0.0
                    port: 80
                client_max_body_size: 0
                server_name: "{{ inventory_hostname }}"
              locations:
              - location:  /
                proxy:
                  pass: http://localhost:8080
                    #redirect:
                    #original: http://$host
                    #replacement: https://$host
                    #set_header:
                    #- field: Host
                    #  value: $host
                    #- field: X-Real-IP
                    #  value: $remote_addr
                    #- field: X-Forwarded-For
                    #  value: $proxy_add_x_forwarded_for
                    #- field: X-Forwarded-Proto
                    #  value: $scheme
                  buffering: false
                  request_buffering: false
