---

roles:
  - name: nginxinc.nginx
    version: 0.23.1
  - name: nginxinc.nginx_config
    version: 0.5.1
  - name: lkiesow.dnf_autoupdate
    version: 2.0.1
  - src: geerlingguy.certbot
    version: 5.0.2

collections:
  - community.crypto
