---

- name: Ensure required directories exist and have the right permissions
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_home }}", mode: "0755" }
    - { path: "{{ buildbot_config_master }}", mode: "0755" }
    - { path: "{{ buildbot_secrets_master }}", mode: "0700" }

- name: Template Buildbot configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: 0600
    force: yes
  become: yes
  with_items:
    - { src: "docker-compose.yml", dest: "{{ buildbot_home }}/docker-compose.yml" }
    - { src: "db.env", dest: "{{ buildbot_home }}/db.env" }
    - { src: "master.cfg", dest: "{{ buildbot_config_master }}/master.cfg" }
    - { src: "builders.py", dest: "{{ buildbot_config_master }}/builders.py" }
    - { src: "build.py", dest: "{{ buildbot_config_master }}/build.py" }
    - { src: "common.py", dest: "{{ buildbot_config_master }}/common.py" }
    - { src: "debs.py", dest: "{{ buildbot_config_master }}/debs.py" }
    - { src: "markdown.py", dest: "{{ buildbot_config_master }}/markdown.py" }
    - { src: "database.py", dest: "{{ buildbot_config_master }}/database.py" }
    - { src: "reports.py", dest: "{{ buildbot_config_master }}/reports.py" }
    - { src: "rpms.py", dest: "{{ buildbot_config_master }}/rpms.py" }
    - { src: "schedulers.py", dest: "{{ buildbot_config_master }}/schedulers.py" }
    - { src: "deb_repo.py", dest: "{{ buildbot_config_master }}/deb_repo.py" }
    - { src: "rpm_repo.py", dest: "{{ buildbot_config_master }}/rpm_repo.py" }
    - { src: "ansible.py", dest: "{{ buildbot_config_master }}/ansible.py" }
    - { src: "buildbot.conf", dest: "{{ buildbot_home }}/nginx-config/buildbot.conf" }
    - { src: "nexus.conf", dest: "{{ buildbot_home }}/nginx-config/nexus.conf" }
  notify: "Start Buildbot"

- name: Template Buildbot public support files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
    force: yes
  become: yes
  with_items:
    - { src: "cleaner.py", dest: "{{ buildbot_home }}/cleaner.py", mode: "644" }

- name: Template Buildbot private support files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: 0600
    force: yes
  become: yes
  with_items:
    - { src: "secrets/changehook.passwd", dest: "{{ buildbot_config_master }}/changehook.passwd" }
    - { src: "secrets/crowdin.key", dest: "{{ buildbot_secrets_master }}/crowdin.key" }
    - { src: "secrets/signing.key", dest: "{{ buildbot_secrets_master }}/signing.key" }
    - { src: "secrets/repo.username", dest: "{{ buildbot_secrets_master }}/repo.username" }
    - { src: "secrets/repo.password", dest: "{{ buildbot_secrets_master }}/repo.password" }
    - { src: "secrets/stable", dest: "{{ buildbot_secrets_master }}/stable" }
    - { src: "secrets/legacy", dest: "{{ buildbot_secrets_master }}/legacy" }
    - { src: "secrets/develop", dest: "{{ buildbot_secrets_master }}/develop" }
    - { src: "secrets/settings.xml", dest: "{{ buildbot_secrets_master }}/settings.xml" }
    - { src: "secrets/s3.access_key", dest: "{{ buildbot_secrets_master }}/s3.access_key" }
    - { src: "secrets/s3.secret_key", dest: "{{ buildbot_secrets_master }}/s3.secret_key" }

