---

- name: Ensure Buildbot directories exists and has the right permissions
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_config_worker }}", mode: "0700" }
    - { path: "{{ buildbot_config_worker }}/envs", mode: "0700" }

- name: Template Buildbot public support files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
    force: yes
  become: yes
  with_items:
    - { src: "mini-dinstall.conf", dest: "{{ buildbot_config_worker }}/mini-dinstall.conf", mode: "644" }
    - { src: "opencast-ingest.sh", dest: "{{ buildbot_config_worker }}/opencast-ingest.sh", mode: "644" }
    - { src: "deb_sign.sh", dest: "{{ buildbot_config_worker }}/deb_sign.sh", mode: "755" }
    - { src: "envs/stable-allinone", dest: "{{ buildbot_config_worker }}/envs/stable-allinone", mode: "0644" }
    - { src: "envs/develop-allinone", dest: "{{ buildbot_config_worker }}/envs/develop-allinone", mode: "0644" }
    - { src: "envs/legacy-allinone", dest: "{{ buildbot_config_worker }}/envs/legacy-allinone", mode: "0644" }

- name: Adding ssh host config data to workers
  blockinfile:
    path: "{{ buildbot_home }}/.ssh/config"
    create: yes
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "0644"
    block: "{{ lookup('template', 'roles/buildbot-config/templates/ssh_config') }}"
  become: yes
