---

- name: Ensure Buildbot worker directories are empty
  file:
    state: absent
    path: "{{ item.path }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_config_worker }}", mode: "0700" }

- name: Ensure Buildbot worker directories exists and has the right permissions
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_config_worker }}", mode: "0700" }
    - { path: "{{ buildbot_config_worker }}/envs", mode: "0700" }

- name: Template Buildbot public support files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
    force: yes
  become: yes
  with_items:
    - { src: "envs/stable-allinone", dest: "{{ buildbot_config_worker }}/envs/stable-allinone", mode: "0644" }
    - { src: "envs/develop-allinone", dest: "{{ buildbot_config_worker }}/envs/develop-allinone", mode: "0644" }
    - { src: "envs/legacy-allinone", dest: "{{ buildbot_config_worker }}/envs/legacy-allinone", mode: "0644" }
