all:
  children:
    uos:
      hosts:
        develop.opencast.org:
        pkg.opencast.org:
        register.opencast.org:
    eth:
      hosts:
        oc-demo.ethz.ch:
    fau:
      hosts:
        stable.opencast.org:
        legacy.opencast.org:
        #ubt00.opencast.rrze.net:
        #ubt01.opencast.rrze.net:
        ubt02.opencast.rrze.net:
