all:
  children:
    uos:
      hosts:
        develop.opencast.org:
        pkg.opencast.org:
        register.opencast.org:
    fau:
      hosts:
        stable.opencast.org:
        legacy.opencast.org:
        ubt02.opencast.rrze.net:
