---

#Worker settings
name: ci-opencast-org

#Master settings
login_user: greglogan
mail_to: "gregorydlogan@gmail.com"
docker_image_user: "greglogan"
source_rpm_repo_url: "https://github.com/gregorydlogan/opencast-rpm-specs.git"

send_mail_notifications: True
send_gh_notifications: True
push_crowdin: True
max_builds: 2
rpm_repo_fragment: "/srv/www/pkg.opencast.org/rpms"
deb_repo_fragment: "/srv/www/pkg.opencast.org/debs"

s3_host: https://s3.tik.uni-stuttgart.de:8082
s3_public_bucket: opencast-community
s3_private_bucket: oepncast-community-private

crowdin_api_key: "{{ lookup('passwordstore', 'crowdin.com/api-key') }}"

github_client_id: "{{ lookup('passwordstore', 'github.com/oauth-id') }}"
github_client_secret:  "{{ lookup('passwordstore', 'github.com/oauth-secret') }}"

github_hook_user: "{{ lookup('passwordstore', 'github.com/hook-user') }}"
github_hook_pass: "{{ lookup('passwordstore', 'github.com/hook-pass') }}"
github_hook_secret:  "{{ lookup('passwordstore', 'github.com/hook-secret') }}"

github_token:  "{{ lookup('passwordstore', 'github.com/api-token') }}"

signing_key: "{{ lookup('passwordstore', 'gpg/nightly/key returnall=true') }}"
signing_key_id: 048D039F1DAE53EA0357ED824917F260EA15B53F

repo_username: "{{ lookup('passwordstore', 'pkg.opencast.org/qaservers/user') }}"
repo_password: "{{ lookup('passwordstore', 'pkg.opencast.org/qaservers/pass') }}"

public_s3_access_key: "{{ lookup('passwordstore', 's3.tik.uni-stuttgart.de/access_key') }}"
public_s3_secret_key: "{{ lookup('passwordstore', 's3.tik.uni-stuttgart.de/secret_key') }}"

