version: '2'
services:
  maria:
    image: mariadb:10
    restart: always
    ports:
      - "127.0.0.1:3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=1

  mysql56:
    image: mysql:5.6
    restart: always
    ports:
      - "127.0.0.1:3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=1

  mysql57:
    image: mysql:5.7
    restart: always
    ports:
      - "127.0.0.1:3309:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_ROOT_HOST=%
      - MYSQL_INITDB_SKIP_TZINFO=1
