---

- name: Ensure Buildbot directories exists and has the right permissions
  file:
    state: directory
    path: "{{ item.path }}"
    owner: "{{ buildbot_user }}"
    group: "{{ buildbot_user }}"
    mode: "{{ item.mode }}"
  become: yes
  with_items:
    - { path: "{{ buildbot_home }}", mode: "0755" }
    - { path: "{{ buildbot_home }}/buildbot-config", mode: "0700" }
    - { path: "{{ buildbot_home }}/.ssh", mode: "0700" }
    - { path: "{{ buildbot_home }}/m2", mode: "0700" }
    - { path: "{{ buildbot_home }}/ansible", mode: "0700" }
    - { path: "{{ buildbot_home }}/builds", mode: "0700" }

